### PR TITLE
Improve script change detection, avoid unnecessary deletions

### LINKED ISSUE #16: Switching between debug/not scripts causes make cmdlet failure
Steps to reproduce:

1) Build mod in default/release (must be successful)
2) Attempt to build the mod in debug

Expected outcome: success
Actual outcome:; 

```
Compiling base game scripts...
Log: Executing Class UnrealEd.MakeCommandlet
No scripts need recompiling.

Success - 0 error(s), 0 warning(s) (0 Unique Errors, 0 Unique Warnings)

Execution of commandlet took:  0.69 seconds


Compiled base game scripts.
Compiling mod scripts...
Log: Executing Class UnrealEd.MakeCommandlet
--------------------Core - Debug--------------------
Package Core was compiled in release mode, recompiling in debug
Error, Failed to delete ..\..\XComGame\Script\Core.u
Error, Failed to delete ..\..\XComGame\Script\GFxUI.u
Error, Failed to delete ..\..\XComGame\Script\GameFramework.u
Error, Failed to delete ..\..\XComGame\Script\IpDrv.u
Error, Failed to delete ..\..\XComGame\Script\OnlineSubsystemSteamworks.u
Error, Failed to delete ..\..\XComGame\Script\XComGame.u

Warning/Error Summary
---------------------
Error, Failed to delete ..\..\XComGame\Script\Core.u
Error, Failed to delete ..\..\XComGame\Script\GFxUI.u
Error, Failed to delete ..\..\XComGame\Script\GameFramework.u
Error, Failed to delete ..\..\XComGame\Script\IpDrv.u
Error, Failed to delete ..\..\XComGame\Script\OnlineSubsystemSteamworks.u
Error, Failed to delete ..\..\XComGame\Script\XComGame.u

Failure - 6 error(s), 0 warning(s) (6 Unique Errors, 0 Unique Warnings)

Execution of commandlet took:  3.93 seconds


Failed compiling mod scripts
```

3) Build again in debug

```
Compiling base game scripts...
Log: Executing Class UnrealEd.MakeCommandlet
--------------------Core - Debug--------------------
Package Core was compiled in release mode, recompiling in debug
Analyzing...
Scripts successfully compiled - saving package 'C:\Steam\steamapps\common\XCOM 2 War of the Chosen SDK\binaries\Win64\..\..\XComGame\Script\Core.u'
--------------------Engine - Debug--------------------
Analyzing...
Scripts successfully compiled - saving package 'C:\Steam\steamapps\common\XCOM 2 War of the Chosen SDK\binaries\Win64\..\..\XComGame\Script\Engine.u'
--------------------GFxUI - Debug--------------------
```

It appears that on the first build invocation the base game scripts `make` doesn't see that the mode has changed for some reason.

Note that building first in debug and then switching to release produces the exact same result

cc @robojumper - I have no idea how the `make` cmdlet works

### LINKED ISSUE #20: Track `Globals.uci` modifications to rebuild when necessary
The script compiler recompiles a package if any of its sources are newer than the compiled package. However,
`Globals.uci` is always a dependency of every package but the script compiler doesn't check it for changes (and the current build tool implementation re-assembles its contents every run).

We need to delete all script packages if the `Globals.uci` file changes.

### LINKED ISSUE #22: `publishID` should be `long`
This isn't caught by the HL because both stable and beta have low enough UGC ids but they did overflow `int` recently.

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #16, Fixes #20

Also fixes #22 while I'm at it.

### CODE REVIEW

**Comment by robojumper** [comment]
I'm not sure what the explicit deletions of the compiled project were for, but since all Robocopy invocations use `/MIR` (mirror), this shouldn't cause extraneous files. This is required to get acceptable warm build times for lwotc, which has 3.5GB of content files for a total of 7GB unnecessary copies.

**Comment by Xymanek** [comment]
> I'm not sure what the explicit deletions of the compiled project were for

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/issues/440. Pretty sure I also replicated the issue with the latest "version" of the build script, which is why I added the deletion of the "deployed" folder

**Comment by robojumper** [comment]
Ah great, that would be https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/master@{2020-02-4}/.scripts/build.ps1, which didn't use Robocopy and instead just `Copy-Item`.

**Comment by Xymanek** [comment]
Well, if it correctly gets rid of the now-deleted files, then I don't mind the underlying implementation 😄

**Pull request merged**
